import RootProvider from "@/Context/RootProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import QueryProvider from "@/Providers/queryProvider";
import ReduxProvider from "../../redux/redux-provider/ReduxProvider";
import { SocketProvider } from "@/Context/SocketProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Toaster position="top-center" />
          <RootProvider>
            <SocketProvider>
              <QueryProvider>{children}</QueryProvider>
            </SocketProvider>
          </RootProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
